### ISSUE TITLE
rodar o projeto final

### ISSUE THREAD

**Issue by luismareze** [cbcaio/code-delivery#1]
Bom dia,

Achei interessante todo o curso.
Existe a possibilidade de rodar um git clone e rodar esse projeto como um todo sem fazer todas as etapas?

**Comment by cbcaio** [comment]
Oi Luis, bom dia, 

eu não terminei de fazer o curso, mas você pode pegar ele no ultimo estado fazendo um clone do https://github.com/CbCaio/code-delivery/releases/tag/cap14 . Da para ter uma ideia do codigo e como funciona apenas lendo as etapas.

Esse repositorio eu fiz com intuito de guardar o que aprendi mesmo, não é um sistema completo para ser usado, mas fico feliz se você conseguir aprender qualquer coisa vendo ele :)

Qualquer dúvida estou sempre no slack do laravel brasil.
